language: php

php:
  - 5.4

services:
  - mongodb
  - memcached

before_install:
  - sudo apt-get install vsftpd
  - sudo sed -i '/anonymous_enable/c\anonymous_enable=YES' /etc/vsftpd.conf
  - sudo sed -i '/write_enable/c\write_enable=YES' /etc/vsftpd.conf
  - sudo sed -i '/local_enable/c\local_enable=YES' /etc/vsftpd.conf
  - sudo sed -i '/ftpd_banner/c\ftpd_banner=Welcome to Vegas Ftp Test Server' /etc/vsftpd.conf
  - sudo service vsftpd restart
  - sudo groupadd ftp-users
  - sudo mkdir /home/ftp-user
  - sudo chmod 777 /home/ftp-user
  - sudo useradd -g ftp-users -d /home/ftp-user ftp-user
  - echo -e "test1234\ntest1234" | sudo passwd ftp-user
  - sudo chown ftp-user:ftp-users /home/ftp-user
  - sudo touch /home/ftp-user/hello.txt
  - sudo sh -c 'echo "Hello Vegas" > /home/ftp-user/hello.txt'

before_script:
  - phpenv config-add travis/php.ini
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v1.3.4
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
